#!/usr/bin/env python3
"""Build the firmware's binary assets.

Cards:  assets/cards/NN.webp (Rider-Waite-Smith majors), or
        assets/decks/<id>/NN.webp for additional decks
        -> data/<env>/decks/<id>/NN_168x295.565
        Raw RGB565, little-endian uint16, row-major, no header. The firmware
        blits these straight into its PSRAM framebuffer.

Fonts:  assets/fonts/Lora-*.ttf (SIL OFL) rasterised through FreeType into
        8-bit alpha glyph tables -> src/fonts/*.h. The firmware alpha-blends
        them itself; Arduino_GFX's 1-bit fonts are not used.

Run with a Python that has Pillow (with FreeType and WebP, which the wheels
on PyPI include):

    python3 -m venv .venv && .venv/bin/pip install pillow
    .venv/bin/python scripts/build_assets.py
"""
import os
import struct
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CARD_SRC = os.path.join(ROOT, "assets", "cards")  # default RWS source
EXTRA_DECKS_DIR = os.path.join(ROOT, "assets", "decks")
DATA_DIR = os.path.join(ROOT, "data")
FONT_OUT = os.path.join(ROOT, "src", "fonts")
FONT_DIR = os.path.join(ROOT, "assets", "fonts")

# One stored bitmap is sampled for both views. Keeping only this source size
# makes five Major-only decks fit in the round board's enlarged filesystem.
DECK_SIZE = (168, 295)
MAX_DECKS = 5


def deck_sources():
    """Return RWS first, followed by any added deck asset directories."""
    sources = {"rws": CARD_SRC}
    if os.path.isdir(EXTRA_DECKS_DIR):
        for deck_id in sorted(os.listdir(EXTRA_DECKS_DIR)):
            source = os.path.join(EXTRA_DECKS_DIR, deck_id)
            if os.path.isdir(source) and not deck_id.startswith("."):
                sources[deck_id] = source
    if len(sources) > MAX_DECKS:
        raise SystemExit("at most %d installed decks fit this image budget" % MAX_DECKS)
    return sources

# name, file, pixel size, variation weight (None = default instance)
FONTS = [
    ("lora_title", "Lora-VariableFont_wght.ttf", 26, 500),
    ("lora_head", "Lora-VariableFont_wght.ttf", 18, 600),
    ("lora_body", "Lora-VariableFont_wght.ttf", 15, 400),
    ("lora_italic", "Lora-Italic-VariableFont_wght.ttf", 15, 400),
    ("lora_read", "Lora-VariableFont_wght.ttf", 17, 400),
    ("lora_read_italic", "Lora-Italic-VariableFont_wght.ttf", 17, 400),
    # The meaning page, two notches up from the reading sizes.
    ("lora_label", "Lora-VariableFont_wght.ttf", 16, 600),
    ("lora_name", "Lora-VariableFont_wght.ttf", 34, 500),
    ("lora_keys", "Lora-Italic-VariableFont_wght.ttf", 19, 400),
    ("lora_meaning", "Lora-VariableFont_wght.ttf", 21, 400),
    ("lora_small", "Lora-VariableFont_wght.ttf", 12, 600),
]
FIRST, LAST = 32, 126


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def build_cards(env, deck_id, source_dir):
    out_dir = os.path.join(DATA_DIR, env, "decks", deck_id)
    os.makedirs(out_dir, exist_ok=True)
    total = 0
    for n in range(22):
        src = os.path.join(source_dir, "%02d.webp" % n)
        im = Image.open(src).convert("RGB")
        w, h = DECK_SIZE
        small = im.resize((w, h), Image.LANCZOS)
        px = small.load()
        out = bytearray(w * h * 2)
        i = 0
        for y in range(h):
            for x in range(w):
                r, g, b = px[x, y]
                struct.pack_into("<H", out, i, rgb565(r, g, b))
                i += 2
        path = os.path.join(out_dir, "%02d_%dx%d.565" % (n, w, h))
        with open(path, "wb") as f:
            f.write(out)
        total += len(out)
    print("cards: %s/%s 22 x %s -> %s (%d KB)" %
          (env, deck_id, DECK_SIZE, os.path.relpath(out_dir, ROOT), total // 1024))


def load_font(file, size, weight):
    font = ImageFont.truetype(os.path.join(FONT_DIR, file), size)
    if weight is not None:
        try:
            font.set_variation_by_axes([weight])
        except Exception as e:  # noqa: BLE001
            print("  (variation unavailable for %s: %s)" % (file, e))
    return font


def build_font(name, file, size, weight):
    font = load_font(file, size, weight)
    ascent, descent = font.getmetrics()
    glyphs = []
    alpha = bytearray()
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        # bbox relative to the baseline-left origin: y0 < 0 is above baseline.
        x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        adv = int(round(font.getlength(ch)))
        if w == 0 or h == 0:
            glyphs.append((len(alpha), 0, 0, 0, 0, adv))
            continue
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
        glyphs.append((len(alpha), w, h, x0, y0, adv))
        alpha += img.tobytes()

    line_h = ascent + descent
    path = os.path.join(FONT_OUT, name + ".h")
    with open(path, "w") as f:
        f.write("// Generated by scripts/build_assets.py from %s @ %dpx" % (file, size))
        f.write(" wght %s. Do not edit.\n" % weight)
        f.write("#pragma once\n#include \"../aafont.h\"\n\n")
        f.write("static const uint8_t %s_alpha[] = {\n" % name)
        for i in range(0, len(alpha), 24):
            f.write("  " + ",".join(str(b) for b in alpha[i:i + 24]) + ",\n")
        f.write("};\n\n")
        f.write("static const AaGlyph %s_glyphs[] = {\n" % name)
        for off, w, h, xo, yo, adv in glyphs:
            f.write("  {%d, %d, %d, %d, %d, %d},\n" % (off, w, h, xo, yo, adv))
        f.write("};\n\n")
        f.write("extern const AaFont %s;\nconst AaFont %s = {%s_alpha, %s_glyphs, %d, %d, %d, %d};\n"
                % (name, name, name, name, FIRST, LAST, line_h, ascent))
    print("font: %-12s %s %dpx -> %s (%d KB alpha, line %d, ascent %d)"
          % (name, file, size, os.path.relpath(path, ROOT), len(alpha) // 1024, line_h, ascent))


def main():
    what = sys.argv[1:] or ["cards", "fonts"]
    if "cards" in what:
        for env in ("amoled-175-round",):
            for deck_id, source_dir in deck_sources().items():
                build_cards(env, deck_id, source_dir)
    if "fonts" in what:
        os.makedirs(FONT_OUT, exist_ok=True)
        for spec in FONTS:
            build_font(*spec)


if __name__ == "__main__":
    main()
