#!/usr/bin/env python3
"""Build the firmware's binary assets.

Cards:  assets/cards/NN.webp (1480x2600 Rider-Waite-Smith majors)
        -> data/<env>/cards/NN_WxH.565 for each size that env uses
        Raw RGB565, little-endian uint16, row-major, no header. The firmware
        blits these straight into its PSRAM framebuffer.

Fonts:  assets/fonts/Lora-*.ttf (SIL OFL) rasterised through FreeType into
        8-bit alpha glyph tables -> src/fonts/*.h. The firmware alpha-blends
        them itself; Arduino_GFX's 1-bit fonts are not used.

Run with a Python that has Pillow (with FreeType and WebP, which the wheels
on PyPI include):

    python3 -m venv .venv && .venv/bin/pip install pillow
    .venv/bin/python scripts/build_assets.py
"""
import os
import struct
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CARD_SRC = os.path.join(ROOT, "assets", "cards")
DATA_DIR = os.path.join(ROOT, "data")
FONT_OUT = os.path.join(ROOT, "src", "fonts")
FONT_DIR = os.path.join(ROOT, "assets", "fonts")

# Per PlatformIO env: (spread size, full-screen size). Must match cards.h.
CARD_SIZES = {
    "amoled-175-round": [(120, 211), (224, 394)],
    "amoled-18": [(104, 183), (250, 440)],
}

# name, file, pixel size, variation weight (None = default instance)
FONTS = [
    ("lora_title", "Lora-VariableFont_wght.ttf", 26, 500),
    ("lora_head", "Lora-VariableFont_wght.ttf", 18, 600),
    ("lora_body", "Lora-VariableFont_wght.ttf", 15, 400),
    ("lora_italic", "Lora-Italic-VariableFont_wght.ttf", 15, 400),
    ("lora_small", "Lora-VariableFont_wght.ttf", 12, 600),
]
FIRST, LAST = 32, 126


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def build_cards(env, sizes):
    out_dir = os.path.join(DATA_DIR, env, "cards")
    os.makedirs(out_dir, exist_ok=True)
    total = 0
    for n in range(22):
        src = os.path.join(CARD_SRC, "%02d.webp" % n)
        im = Image.open(src).convert("RGB")
        for (w, h) in sizes:
            small = im.resize((w, h), Image.LANCZOS)
            px = small.load()
            out = bytearray(w * h * 2)
            i = 0
            for y in range(h):
                for x in range(w):
                    r, g, b = px[x, y]
                    struct.pack_into("<H", out, i, rgb565(r, g, b))
                    i += 2
            path = os.path.join(out_dir, "%02d_%dx%d.565" % (n, w, h))
            with open(path, "wb") as f:
                f.write(out)
            total += len(out)
    print("cards: %s 22 x %s -> %s (%d KB)" % (env, sizes, os.path.relpath(out_dir, ROOT), total // 1024))


def load_font(file, size, weight):
    font = ImageFont.truetype(os.path.join(FONT_DIR, file), size)
    if weight is not None:
        try:
            font.set_variation_by_axes([weight])
        except Exception as e:  # noqa: BLE001
            print("  (variation unavailable for %s: %s)" % (file, e))
    return font


def build_font(name, file, size, weight):
    font = load_font(file, size, weight)
    ascent, descent = font.getmetrics()
    glyphs = []
    alpha = bytearray()
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        # bbox relative to the baseline-left origin: y0 < 0 is above baseline.
        x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        adv = int(round(font.getlength(ch)))
        if w == 0 or h == 0:
            glyphs.append((len(alpha), 0, 0, 0, 0, adv))
            continue
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
        glyphs.append((len(alpha), w, h, x0, y0, adv))
        alpha += img.tobytes()

    line_h = ascent + descent
    path = os.path.join(FONT_OUT, name + ".h")
    with open(path, "w") as f:
        f.write("// Generated by scripts/build_assets.py from %s @ %dpx" % (file, size))
        f.write(" wght %s. Do not edit.\n" % weight)
        f.write("#pragma once\n#include \"../aafont.h\"\n\n")
        f.write("static const uint8_t %s_alpha[] = {\n" % name)
        for i in range(0, len(alpha), 24):
            f.write("  " + ",".join(str(b) for b in alpha[i:i + 24]) + ",\n")
        f.write("};\n\n")
        f.write("static const AaGlyph %s_glyphs[] = {\n" % name)
        for off, w, h, xo, yo, adv in glyphs:
            f.write("  {%d, %d, %d, %d, %d, %d},\n" % (off, w, h, xo, yo, adv))
        f.write("};\n\n")
        f.write("extern const AaFont %s;\nconst AaFont %s = {%s_alpha, %s_glyphs, %d, %d, %d, %d};\n"
                % (name, name, name, name, FIRST, LAST, line_h, ascent))
    print("font: %-12s %s %dpx -> %s (%d KB alpha, line %d, ascent %d)"
          % (name, file, size, os.path.relpath(path, ROOT), len(alpha) // 1024, line_h, ascent))


def main():
    what = sys.argv[1:] or ["cards", "fonts"]
    if "cards" in what:
        for env, sizes in CARD_SIZES.items():
            build_cards(env, sizes)
    if "fonts" in what:
        os.makedirs(FONT_OUT, exist_ok=True)
        for spec in FONTS:
            build_font(*spec)


if __name__ == "__main__":
    main()
