#!/usr/bin/env python3
"""Compile the language sources into the packs the firmware loads.

    assets/lang/<lang>/ui.json        UI and reading-engine strings
    assets/lang/<lang>/<deck>.json    card text, pair prose, reading templates
        ->
    data/<env>/lang/<lang>/ui.pack
    data/<env>/lang/<lang>/<deck>.pack
    data/<env>/lang/index.json        the languages the settings screen offers
    src/string_ids.h                  the UI string enum, generated from `en`

Adding a language is these files plus `pio run -t uploadfs`. It is never a
firmware build.

Pack format, little-endian, read by packLoad() in src/strings.cpp:

    magic "TAP1"          4 bytes
    count                 uint16
    reserved              uint16
    offsets[count + 1]    uint32, byte offsets into blob; the last is its size
    blob                  count NUL-terminated UTF-8 strings

`en` is canonical: another language must define exactly the same UI keys, and
its deck files must hold the same counts. The build fails rather than shipping
a pack that would read a missing string at runtime.
"""
import json
import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LANG_SRC = os.path.join(ROOT, "assets", "lang")
DATA_DIR = os.path.join(ROOT, "data")
ENVS = ("amoled-175-round",)
BASE = "en"

MAGIC = b"TAP1"
# Kept in step with src/deck.h. The engine reads the reading style through
# these fixed-length runs, so a deck file that disagrees is a build error.
ROWS, ARC, PLANE, DOMINANT, TRANSITION = 4, 4, 4, 5, 4
CARD_FIELDS = ("name", "ruler", "keywords", "essence",
               "past", "present", "future", "question")


def load(path):
    with open(path, encoding="utf8") as f:
        return json.load(f)


def pack(strings):
    blob = bytearray()
    offsets = []
    for s in strings:
        offsets.append(len(blob))
        blob += s.encode("utf8") + b"\0"
    offsets.append(len(blob))
    out = bytearray(MAGIC)
    out += struct.pack("<HH", len(strings), 0)
    out += struct.pack("<%dI" % len(offsets), *offsets)
    out += blob
    return bytes(out)


def deck_strings(doc, path):
    """Flatten a deck file into the order deckTextLoad() in src/strings.cpp reads."""
    out = [doc["name"]]
    cards = doc["cards"]
    for i, c in enumerate(cards):
        for f in CARD_FIELDS:
            if f not in c:
                raise SystemExit("%s: card %d has no %r" % (path, i, f))
            out.append(c[f])
    out += list(doc["pairs"])
    for key, n in (("rowNames", ROWS), ("rowGlosses", ROWS), ("arc", ARC),
                   ("plane", PLANE), ("dominant", DOMINANT),
                   ("transition", TRANSITION)):
        v = doc[key]
        if len(v) != n:
            raise SystemExit("%s: %r has %d entries, expected %d" % (path, key, len(v), n))
        out += list(v)
    out.append(doc["hidden"])
    out.append(doc["hiddenRepeated"])
    return out, len(cards), len(doc["pairs"])


def write_ids(keys, decks):
    path = os.path.join(ROOT, "src", "string_ids.h")
    with open(path, "w", encoding="utf8") as f:
        f.write("// Generated by scripts/build_strings.py from assets/lang/%s/ui.json.\n"
                "// Do not edit: add a key to that file and re-run the script.\n"
                "#pragma once\n#include <stdint.h>\n\n"
                "enum StringId : uint16_t {\n" % BASE)
        for i, k in enumerate(keys):
            f.write("  %s = %d,\n" % (k, i))
        f.write("  STRING_COUNT = %d,\n};\n\n" % len(keys))
        f.write("// Deck pack layout, mirrored by deck_strings() in the build script.\n"
                "static const uint8_t DECK_CARD_FIELDS = %d;\n" % len(CARD_FIELDS))
        f.write("enum DeckCardField : uint8_t {\n")
        for i, name in enumerate(CARD_FIELDS):
            f.write("  DCF_%s = %d,\n" % (name.upper(), i))
        f.write("};\n")
    return path


def main():
    langs = sorted(d for d in os.listdir(LANG_SRC)
                   if os.path.isdir(os.path.join(LANG_SRC, d)))
    if BASE not in langs:
        raise SystemExit("no assets/lang/%s" % BASE)

    base_ui = load(os.path.join(LANG_SRC, BASE, "ui.json"))
    keys = list(base_ui["strings"])
    base_decks = {}
    for name in sorted(os.listdir(os.path.join(LANG_SRC, BASE))):
        if name.endswith(".json") and name != "ui.json":
            doc = load(os.path.join(LANG_SRC, BASE, name))
            _, cards, pairs = deck_strings(doc, name)
            base_decks[name] = (cards, pairs)

    print("ids: %s (%d strings)" % (os.path.relpath(write_ids(keys, base_decks), ROOT), len(keys)))

    index = []
    for lang in langs:
        src = os.path.join(LANG_SRC, lang)
        ui = load(os.path.join(src, "ui.json"))
        missing = [k for k in keys if k not in ui["strings"]]
        extra = [k for k in ui["strings"] if k not in keys]
        if missing or extra:
            raise SystemExit("%s/ui.json: missing %s, unknown %s" % (lang, missing, extra))
        index.append({"code": ui.get("code", lang), "name": ui["language"]})

        for env in ENVS:
            out = os.path.join(DATA_DIR, env, "lang", lang)
            os.makedirs(out, exist_ok=True)
            blob = pack([ui["strings"][k] for k in keys])
            open(os.path.join(out, "ui.pack"), "wb").write(blob)
            total = len(blob)

            for name, (cards, pairs) in base_decks.items():
                p = os.path.join(src, name)
                if not os.path.isfile(p):
                    raise SystemExit("%s: no %s" % (lang, name))
                doc = load(p)
                strings, c, pr = deck_strings(doc, p)
                if (c, pr) != (cards, pairs):
                    raise SystemExit("%s/%s: %d cards / %d pairs, %s has %d / %d"
                                     % (lang, name, c, pr, BASE, cards, pairs))
                blob = pack(strings)
                open(os.path.join(out, name[:-5] + ".pack"), "wb").write(blob)
                total += len(blob)
            print("lang: %-6s %s -> %d KB" % (lang, env, (total + 1023) // 1024))

    for env in ENVS:
        p = os.path.join(DATA_DIR, env, "lang", "index.json")
        with open(p, "w", encoding="utf8") as f:
            json.dump(index, f, ensure_ascii=False, indent=1)
        print("index: %s (%d languages)" % (os.path.relpath(p, ROOT), len(index)))


if __name__ == "__main__":
    main()
