// Anti-aliased glyph tables generated by scripts/build_assets.py.
// 8-bit alpha, row-major, no padding. yo is the glyph top relative to the
// baseline (negative = above). Rendering lives in text.cpp.
#pragma once
#include <stdint.h>

struct AaGlyph {
  uint32_t off;   // offset into alpha[]
  uint8_t w, h;
  int8_t xo, yo;
  uint8_t adv;
};

// glyphs[] is two blocks. The first is dense: one entry per codepoint from
// first to last, which is printable ASCII and covers almost every character
// drawn. The second holds the accented and typographic codepoints, in the
// same order as codes[], found by binary search.
//
// codes[] is uint16_t, so the format stops at U+FFFF. That is deliberate: it
// reaches every Latin, Greek and Cyrillic script and excludes CJK, which a
// per-glyph alpha table of this shape could not carry anyway.
struct AaFont {
  const uint8_t *alpha;
  const AaGlyph *glyphs;
  const uint16_t *codes;   // sorted, `extra` entries, all above `last`
  uint16_t extra;
  uint8_t first, last;
  uint8_t lineH;
  uint8_t ascent;
};
