// Anti-aliased glyph tables generated by scripts/build_assets.py.
// 8-bit alpha, row-major, no padding. yo is the glyph top relative to the
// baseline (negative = above). Rendering lives in text.cpp.
#pragma once
#include <stdint.h>

struct AaGlyph {
  uint32_t off;   // offset into alpha[]
  uint8_t w, h;
  int8_t xo, yo;
  uint8_t adv;
};

struct AaFont {
  const uint8_t *alpha;
  const AaGlyph *glyphs;
  uint8_t first, last;
  uint8_t lineH;
  uint8_t ascent;
};
