#include "deck_content.h"

// GPTarot: the same major identities viewed through a shorter, image-led and
// emotionally direct register. These are original device texts, not copied
// from the GPTarot.ai site.
const uint8_t GPTAROT_VALUES[MAJOR_COUNT] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
    12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
};

const Glyph GPTAROT_GLYPHS[MAJOR_COUNT] = {
    G_AIR, G_MERCURY, G_MOON, G_VENUS, G_ARIES, G_TAURUS, G_GEMINI,
    G_CANCER, G_LEO, G_VIRGO, G_JUPITER, G_LIBRA, G_WATER, G_SCORPIO,
    G_SAGITTARIUS, G_CAPRICORN, G_MARS, G_AQUARIUS, G_PISCES, G_SUN,
    G_FIRE, G_SATURN,
};

const CardInfo GPTAROT_CARDS[MAJOR_COUNT] = {
    {"The Fool", "0", EL_AIR, "Air", "wonder, risk, beginning",
     "The Fool is the image of possibility before it becomes a plan.",
     "You followed a feeling before you could explain it. That was not foolish; it was the only honest beginning available.",
     "The picture is open. Take the next small step and let the path answer you.",
     "A new image is approaching fast. Keep your hands light enough to receive it.",
     "Where could you let curiosity lead for one day?"},
    {"The Magician", "I", EL_AIR, "Mercury", "agency, tools, focus",
     "The Magician turns attention into an instrument.",
     "You had more influence than you admitted, and the image shows where you used it.",
     "Choose one thing and make it vivid. Your attention is the spell in this room.",
     "A chance to shape the scene is coming. Be precise rather than impressive.",
     "What are you ready to make real?"},
    {"The High Priestess", "II", EL_WATER, "the Moon", "silence, depth, signal",
     "The High Priestess is the meaning that appears when the noise stops.",
     "You noticed the hidden current before anyone else did. Do not edit that perception to make it easier to share.",
     "Stay behind the first answer. The quieter signal is the one worth following.",
     "A secret becomes legible when you stop chasing it. Let the veil thin in its own time.",
     "What are you sensing beneath the obvious story?"},
    {"The Empress", "III", EL_EARTH, "Venus", "growth, pleasure, nurture",
     "The Empress is the image of life making more life.",
     "Something generous gave you room to become. Remember the feeling, not just the source.",
     "Put care where you want abundance. Small acts of tending have a long shadow.",
     "What you have been nurturing is close to becoming visible. Receive it without rushing it.",
     "What deserves more of your attention and tenderness?"},
    {"The Emperor", "IV", EL_FIRE, "Aries", "order, boundary, backbone",
     "The Emperor is a clear edge around what matters.",
     "A rule or authority shaped this chapter. Keep the protection; question the fear beneath it.",
     "Make the boundary kind and unmistakable. Structure is here to free the living thing inside it.",
     "You will need to hold your ground soon. Let firmness speak before force does.",
     "Which boundary would make you more available to life?"},
    {"The Hierophant", "V", EL_EARTH, "Taurus", "ritual, teacher, belonging",
     "The Hierophant is a door into a practice shared with others.",
     "An inherited ritual helped you name what mattered. Keep its wisdom, not its costume.",
     "Borrow a structure that supports you. You do not have to invent every answer alone.",
     "A guide or community appears. Notice whether belonging makes your world larger.",
     "What practice helps you remember who you are?"},
    {"The Lovers", "VI", EL_AIR, "Gemini", "choice, attraction, alignment",
     "The Lovers is the image of a choice made with the whole self.",
     "A past yes still lives in the room. Feel what it opened, and what it closed.",
     "Two honest desires are asking to be seen together. Choose by alignment, not by noise.",
     "A meeting or decision brings the heart into focus. Do not offer a partial truth.",
     "What would a full-bodied yes feel like?"},
    {"The Chariot", "VII", EL_WATER, "Cancer", "direction, movement, composure",
     "The Chariot is motion held steady by a living center.",
     "You moved through competing pulls by staying close to your destination.",
     "Keep both opposing feelings in view, then choose the direction that can carry them.",
     "Momentum builds. Speed is less important than knowing which way you are facing.",
     "What is steering you when you are not paying attention?"},
    {"Strength", "VIII", EL_FIRE, "Leo", "courage, warmth, instinct",
     "Strength is the image of power that does not need to dominate.",
     "You softened a difficult force without abandoning yourself. That quiet skill remains yours.",
     "Meet the fierce part gently. It may be protecting the very thing you need to hear.",
     "A charged moment can become intimacy if you stay present instead of performing control.",
     "What would your strength look like without armour?"},
    {"The Hermit", "IX", EL_EARTH, "Virgo", "solitude, signal, lantern",
     "The Hermit is a small light trusted in a large dark.",
     "Distance let a real question rise above the crowd. You were right to make that space.",
     "Withdraw just enough to hear your own pattern. The answer does not need an audience yet.",
     "A quiet guide or a quiet season gives you the missing angle. Go toward the stillness.",
     "What becomes visible only when you stop explaining yourself?"},
    {"Wheel of Fortune", "X", EL_FIRE, "Jupiter", "cycles, timing, turn",
     "The Wheel is the image of a pattern changing its face.",
     "A turn of circumstance carried you farther than effort could. Let luck have its share of the story.",
     "You are between states. Watch the rhythm and place yourself where the next turn can meet you.",
     "The scene changes quickly. Flexibility will serve you better than a perfect prediction.",
     "What pattern is asking to be met differently this time?"},
    {"Justice", "XI", EL_AIR, "Libra", "truth, proportion, choice",
     "Justice is the image that makes the picture honest.",
     "A past choice still has weight. You can acknowledge its cost without becoming its prisoner.",
     "Look straight at the exchange. Give each fact its proper size, including your own needs.",
     "A clear consequence or decision is near. Let accuracy be a form of care.",
     "What becomes fair when you include yourself?"},
    {"The Hanged Man", "XII", EL_WATER, "Water", "pause, reversal, release",
     "The Hanged Man is the image that changes when you stop insisting on the old angle.",
     "A pause rearranged your priorities. The delay was not empty time.",
     "Release the need to force the next frame. Let the upside-down view teach you something.",
     "A suspended interval reveals what urgency kept hidden. Do less, but see more.",
     "Which struggle would loosen if you stopped pulling?"},
    {"Death", "XIII", EL_WATER, "Scorpio", "ending, shedding, renewal",
     "Death is the image of a door closing so the room can change.",
     "An ending made the present possible. Honour the loss without reopening the door.",
     "Let the old form finish. Change is already moving through the empty space.",
     "A clean release brings new color. Do not carry yesterday's costume into it.",
     "What is ready to be finished with love?"},
    {"Temperance", "XIV", EL_FIRE, "Sagittarius", "blend, rhythm, measure",
     "Temperance is the image of two currents learning one rhythm.",
     "You found a workable middle by listening to both extremes.",
     "Adjust the mixture. The right balance is alive, not a rule you set once.",
     "Two different needs can cooperate soon. Move slowly enough to notice the blend.",
     "What could become possible if you changed the proportions?"},
    {"The Devil", "XV", EL_EARTH, "Capricorn", "desire, attachment, charge",
     "The Devil is the image of a bond that wants to be seen clearly.",
     "A desire became a habit, then a story about who you had to be.",
     "Look at the chain without shame. Naming the appetite gives you room to choose.",
     "A tempting shortcut arrives. Ask whether it feeds you or only keeps the loop alive.",
     "What are you loyal to because it is familiar?"},
    {"The Tower", "XVI", EL_FIRE, "Mars", "shock, truth, clearing",
     "The Tower is the image that removes what could not remain.",
     "A rupture exposed the weak beam. The surprise was painful, but the truth was useful.",
     "Do not rush to repair the picture. See what the collapse has made visible.",
     "A sudden opening breaks the old arrangement. Keep what is alive and let the rest fall.",
     "What truth would make rebuilding unnecessary?"},
    {"The Star", "XVII", EL_AIR, "Aquarius", "hope, openness, renewal",
     "The Star is the image of trust returned to the body.",
     "Hope came back in a small form. You did not need to believe everything to begin healing.",
     "Let yourself be visible without a shield. The future can meet an undefended heart.",
     "A clean horizon appears. Follow what restores your sense of possibility.",
     "What would you ask for if hope were safe?"},
    {"The Moon", "XVIII", EL_WATER, "Pisces", "dream, ambiguity, instinct",
     "The Moon is the image that makes uncertainty feel alive.",
     "Fear filled in missing details and called them facts. You can redraw the picture now.",
     "Move by small signals. Not every shadow needs to become a conclusion tonight.",
     "A dream or doubt reveals a hidden route. Stay curious while the image shifts.",
     "What are you assuming because the light is low?"},
    {"The Sun", "XIX", EL_FIRE, "the Sun", "joy, clarity, vitality",
     "The Sun is the image that lets nothing hide from warmth.",
     "A clear and joyful moment showed you how simple truth can feel.",
     "Let the good thing be good. You do not need to earn the light by distrusting it.",
     "Confidence and warmth gather around you. Share them without turning them into a performance.",
     "Where is life already saying yes?"},
    {"Judgement", "XX", EL_FIRE, "Fire", "awakening, return, call",
     "Judgement is the image that asks the sleeping self to stand up.",
     "An old version of you ended when you answered a call you could not unhear.",
     "Listen for the invitation beneath the pressure. This is a return to what is most alive.",
     "A second chance arrives with a clearer name. Answer as the person you are now.",
     "What part of you is ready to come back?"},
    {"The World", "XXI", EL_EARTH, "Saturn", "completion, integration, cycle",
     "The World is the image of separate threads becoming one field.",
     "A cycle closed and left you with more of yourself than you began with.",
     "Finish the last visible piece. Let completion be a felt state, not another task.",
     "A larger horizon opens after the circle closes. Carry the lesson, not the burden.",
     "What would completion make room for?"},
};

const DeckPair GPTAROT_PAIRS[] = {
    {0, 21, false, "The Fool and the World make one image of beginning and completion. You may be closer to a new cycle than you think."},
    {1, 2, false, "The Magician and the High Priestess pair action with perception. Make room for both the hand and the hidden signal."},
    {3, 4, false, "The Empress and the Emperor ask growth to meet structure. Give the living thing a container, not a cage."},
    {5, 9, false, "The Hierophant and the Hermit show two ways to learn: through belonging and through solitude. Let each correct the other."},
    {6, 7, true, "The Lovers becoming the Chariot: a choice gains direction. Decide, then let movement teach you what the choice means."},
    {7, 8, true, "The Chariot meets Strength. Momentum becomes presence; steer with warmth, not with clenched hands."},
    {8, 15, false, "Strength beside the Devil puts instinct in the light. Desire is not the enemy, but it should not hold the reins."},
    {10, 16, true, "The Wheel turning into the Tower is a fast change of frame. Let the surprise clear the image instead of defining you."},
    {11, 12, true, "Justice into the Hanged Man: after seeing clearly, release the urge to act immediately."},
    {12, 13, true, "The Hanged Man and Death turn pause into release. The thing you stop forcing may finally be allowed to end."},
    {13, 17, true, "Death opening into the Star is the quiet promise after a clean ending. Protect the new light."},
    {14, 15, false, "Temperance and the Devil ask what kind of pleasure can last. Change the measure, not the aliveness."},
    {16, 17, true, "The Tower followed by the Star: the image breaks, then breath returns. Do not rebuild the old picture."},
    {17, 18, true, "The Star entering the Moon keeps hope alive inside uncertainty. Trust the small light, not the whole map."},
    {18, 19, true, "The Moon becoming the Sun is a fog lifting. Let clarity arrive through experience, not argument."},
    {19, 20, true, "The Sun and Judgement turn joy into a calling. What feels good may also be asking to become useful."},
    {20, 21, true, "Judgement opening into the World gives the call a place to land. Answer by completing something real."},
    {2, 18, false, "The High Priestess and the Moon share a deep-water language. Notice what the dream knows before you translate it."},
    {4, 16, false, "The Emperor and the Tower reveal the difference between structure and rigidity. Keep only what can flex and stand."},
    {6, 15, false, "The Lovers and the Devil make attachment visible. A bond can be intimate without becoming a chain."},
    {9, 10, true, "The Hermit and the Wheel: solitude changes the way you recognize the next turn."},
    {14, 21, false, "Temperance and the World show integration as a lived practice. Wholeness is assembled in daily proportions."},
};
const uint8_t GPTAROT_PAIR_COUNT = sizeof(GPTAROT_PAIRS) / sizeof(GPTAROT_PAIRS[0]);

// Marseille: French card titles, Justice VIII / Strength XI, and a grounded
// reading language based on image, number, posture and practical movement.
const uint8_t MARSEILLE_VALUES[MAJOR_COUNT] = {
    0, 1, 2, 3, 4, 5, 6, 7, 11, 9, 10, 8,
    12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
};

const CardInfo MARSEILLE_CARDS[MAJOR_COUNT] = {
    {"Le Mat", "0", EL_AIR, "", "departure, instinct, road",
     "Le Mat is the unnumbered traveller, carrying possibility rather than proof.",
     "You came from a road without a fixed destination. The lack of a plan kept you moving.",
     "Leave room for the next encounter. The road is the teacher, and the first step is enough.",
     "A new road opens through movement. Do not ask it to promise the whole journey.",
     "What road would you take if arrival were not the point?"},
    {"Le Bateleur", "I", EL_AIR, "", "tools, skill, beginning",
     "Le Bateleur puts the tools of a life on the table.",
     "You learned by trying with what was at hand. That practical intelligence still serves you.",
     "Choose one tool and use it. The beginning becomes real through a simple gesture.",
     "A small opportunity asks for dexterity. Start before the arrangement feels perfect.",
     "What is already in your hands?"},
    {"La Papesse", "II", EL_WATER, "", "book, silence, gestation",
     "La Papesse keeps knowledge until it has ripened enough to be shared.",
     "Something was learned quietly, through watching rather than announcing.",
     "Read the room and the page twice. The useful answer is behind the first impression.",
     "A hidden fact or patient study becomes important. Let time do part of the work.",
     "What needs more time before it is spoken?"},
    {"L'Imperatrice", "III", EL_EARTH, "", "growth, expression, intelligence",
     "L'Imperatrice makes an idea fertile, articulate and alive.",
     "A creative or relational force gave shape to the past. Notice what it taught you to value.",
     "Speak, draw or build the thing that wants form. Growth needs expression.",
     "A productive season approaches. Let your intelligence make the conditions richer.",
     "What wants to be brought into the world?"},
    {"L'Empereur", "IV", EL_FIRE, "", "order, ground, authority",
     "L'Empereur makes a stable place from which action can begin.",
     "A firm structure supported you, or constrained you. Both facts belong in the account.",
     "Set the practical terms. A clear limit protects the work from confusion.",
     "Responsibility arrives with a material shape: a decision, budget, room or role.",
     "What foundation would make you steadier?"},
    {"Le Pape", "V", EL_EARTH, "", "counsel, custom, blessing",
     "Le Pape connects a personal question to a shared wisdom.",
     "A teacher, elder or custom gave the past its language.",
     "Ask for counsel, but keep your judgment. Tradition is useful when it serves life.",
     "A helpful guide or agreement appears. Listen for what can be practiced, not merely admired.",
     "Whose experience could shorten your way?"},
    {"L'Amoureux", "VI", EL_AIR, "", "choice, attachment, crossroads",
     "L'Amoureux is the pause where a choice becomes visible.",
     "An earlier attachment shaped the road. Its sweetness and its cost are both real.",
     "Do not let indecision disguise itself as kindness. Choose what you can stand behind.",
     "A meeting or crossroads asks for a clear preference. The heart needs a direction.",
     "What choice are you postponing by keeping every door open?"},
    {"Le Chariot", "VII", EL_WATER, "", "advance, vehicle, resolve",
     "Le Chariot carries its opposing horses forward through direction.",
     "You advanced by holding competing needs in one frame.",
     "Keep the reins steady and the destination plain. Do not confuse haste with progress.",
     "A journey, move or decisive push gains momentum. Choose the route before the speed.",
     "What direction deserves your full effort?"},
    {"La Force", "XI", EL_FIRE, "", "patience, courage, vitality",
     "La Force joins a human hand to the animal life within it.",
     "You handled a difficult force through patience rather than display.",
     "Work with the living energy in the situation. Gentleness can be a form of command.",
     "A test of courage approaches. Stay close to the body and let steadiness lead.",
     "What strong feeling can you meet without fighting?"},
    {"L'Hermite", "IX", EL_EARTH, "", "lantern, age, search",
     "L'Hermite carries a small light and asks the next step to be enough.",
     "Solitude or experience taught you what noise could not.",
     "Reduce the pace. The right question will be easier to see when fewer things compete for it.",
     "A guide, retreat or patient craft brings the answer closer.",
     "What can only be learned slowly?"},
    {"La Roue de Fortune", "X", EL_FIRE, "", "turning, chance, cycle",
     "La Roue de Fortune shows the situation changing under every fixed assumption.",
     "Chance and circumstance turned the past in a direction you did not choose alone.",
     "Watch for the opening in the turn. Prepare, but do not pretend to control the wheel.",
     "A change of circumstances arrives. Adaptation will be more useful than blame.",
     "What cycle is changing beneath your feet?"},
    {"La Justice", "VIII", EL_AIR, "", "measure, law, consequence",
     "La Justice weighs the act and its result without decoration.",
     "A past decision still defines the terms. Meet its consequence without exaggerating it.",
     "Put the facts in order. Fairness begins with seeing the whole exchange.",
     "A ruling, agreement or correction makes the next step clearer.",
     "What would be fair if you included every person affected?"},
    {"Le Pendu", "XII", EL_WATER, "", "suspension, reversal, offering",
     "Le Pendu makes a pause into a different way of seeing.",
     "A delay or sacrifice changed your perspective more than action could have.",
     "Stop forcing the old route. Let the position reveal what it is asking of you.",
     "Progress arrives through a reversal, a pause or a willing concession.",
     "What could the pause give you that motion cannot?"},
    {"Arcane sans nom", "XIII", EL_WATER, "", "ending, pruning, change",
     "Arcane sans nom clears what has finished so the image can change.",
     "The past contains a clean ending, even if the feelings around it are not clean yet.",
     "Prune without cruelty. The empty space is part of the new arrangement.",
     "A decisive change removes an old burden and makes a different life practical.",
     "What is finished even if you still miss it?"},
    {"Temperance", "XIV", EL_FIRE, "", "exchange, healing, measure",
     "Temperance keeps two vessels moving until the mixture becomes usable.",
     "A compromise or healing practice taught you that balance is made, not found.",
     "Adjust the proportions. Small exchanges can restore a workable middle.",
     "Help, reconciliation or a useful blend becomes possible.",
     "What needs to be combined rather than chosen between?"},
    {"Le Diable", "XV", EL_EARTH, "", "bond, appetite, material pull",
     "Le Diable shows the tie between appetite and the object that feeds it.",
     "A past bargain or habit still has a material grip. See the terms clearly.",
     "Name the attachment without shame, then decide whether its price is still acceptable.",
     "A strong temptation or practical dependency becomes visible. Knowledge restores choice.",
     "What are you maintaining because it is profitable, familiar or desired?"},
    {"La Maison-Dieu", "XVI", EL_FIRE, "", "break, revelation, release",
     "La Maison-Dieu breaks an enclosure and lets the trapped life out.",
     "A disruption exposed the weakness in the old house. It also opened a door.",
     "Do not decorate the broken wall. Clear the site and keep what can be reused.",
     "A sudden event changes the practical arrangement. The truth will save time.",
     "What would you stop protecting if the wall fell?"},
    {"L'Etoile", "XVII", EL_AIR, "", "guidance, openness, renewal",
     "L'Etoile pours trust into the world without trying to own it.",
     "Hope or a helpful example gave the past a direction after difficulty.",
     "Offer what you have freely and keep the channel open. Renewal needs circulation.",
     "A quiet sign, ally or clear hope appears. Follow the direction that restores you.",
     "What small light is already enough to follow?"},
    {"La Lune", "XVIII", EL_WATER, "", "dream, fear, uncertainty",
     "La Lune makes the road uncertain but does not make it unreal.",
     "Fear or imagination colored an earlier chapter. The picture deserves a second look.",
     "Move carefully through incomplete information. Let observation outrank assumption.",
     "A dream, doubt or hidden motive becomes visible. Wait for more light before deciding.",
     "What part of the picture still needs daylight?"},
    {"Le Soleil", "XIX", EL_FIRE, "", "clarity, warmth, success",
     "Le Soleil puts two lives under one clear source of warmth.",
     "A period of openness showed you what mutual joy feels like in practice.",
     "Let the facts be bright. Share the good news without making it complicated.",
     "Recognition, health or a plain success warms the next stage.",
     "What is clear enough to celebrate?"},
    {"Le Jugement", "XX", EL_FIRE, "", "call, return, reckoning",
     "Le Jugement calls what was buried back into relationship with the living.",
     "A past decision or awakening still asks to be acknowledged.",
     "Answer the call by making a concrete change, not by repeating the feeling of it.",
     "A return, announcement or second chance asks you to stand up and participate.",
     "What is asking to be brought back into your life?"},
    {"Le Monde", "XXI", EL_EARTH, "", "completion, passage, whole",
     "Le Monde gathers the four directions into one finished passage.",
     "A cycle completed and gave you a wider sense of where you belong.",
     "Finish what remains and let the result be visible. Completion is a shared fact.",
     "A successful passage opens the next world. Carry the skill, not the old limit.",
     "What would you recognize as complete?"},
};

const DeckPair MARSEILLE_PAIRS[] = {
    {0, 21, false, "Le Mat and Le Monde make a complete road: departure and arrival belong to one passage."},
    {1, 2, false, "Le Bateleur and La Papesse put the visible tool beside the hidden book. Act, then read what the act reveals."},
    {3, 4, false, "L'Imperatrice and L'Empereur join growth to ground. Give the living project a place and a limit."},
    {4, 5, false, "L'Empereur and Le Pape ask whether order comes from your own rule or from a shared custom."},
    {5, 9, false, "Le Pape and L'Hermite offer counsel in two forms: what is handed down and what is learned alone."},
    {6, 7, true, "L'Amoureux becoming Le Chariot: a choice leaves the crossroads and becomes a direction."},
    {7, 8, true, "Le Chariot and La Force turn movement into composure. The strongest hand is the one that keeps the reins steady."},
    {8, 15, false, "La Force beside Le Diable shows the difference between holding desire and being held by it."},
    {10, 16, true, "La Roue de Fortune turning into La Maison-Dieu is change that reveals the structure beneath the change."},
    {11, 12, true, "La Justice into Le Pendu: after measuring the situation, allow the pause to change your judgment."},
    {12, 13, true, "Le Pendu and Arcane sans nom turn suspension into release. What is not forced can finally finish."},
    {13, 17, true, "Arcane sans nom opening into L'Etoile shows hope growing in the space made by pruning."},
    {14, 15, false, "Temperance and Le Diable ask whether appetite can be given a measure without being denied."},
    {16, 17, true, "La Maison-Dieu followed by L'Etoile: the broken enclosure becomes an opening for guidance."},
    {17, 18, true, "L'Etoile and La Lune keep a small light alive while the path remains uncertain."},
    {18, 19, true, "La Lune becoming Le Soleil is uncertainty becoming a fact you can stand in."},
    {19, 20, true, "Le Soleil into Le Jugement turns clarity into a call to act on what has become obvious."},
    {20, 21, true, "Le Jugement into Le Monde gives the call a place in the completed life."},
    {2, 18, false, "La Papesse and La Lune speak in quiet images. Observe before you decide what the picture means."},
    {6, 15, false, "L'Amoureux and Le Diable make attachment visible. A bond becomes healthier when its price can be named."},
    {9, 10, true, "L'Hermite and La Roue: a quiet interval changes how you recognize the next turn."},
    {14, 21, false, "Temperance and Le Monde show wholeness as a repeated practical adjustment, not a final pose."},
};
const uint8_t MARSEILLE_PAIR_COUNT = sizeof(MARSEILLE_PAIRS) / sizeof(MARSEILLE_PAIRS[0]);

static const char *const MARSEILLE_ROW_NAME[4] = {
    "the unnamed beginning", "the table of life", "the human passage", "the complete cycle"};
static const char *const MARSEILLE_ROW_GLOSS[4] = {
    "the road before a fixed role",
    "work, relation and visible circumstance",
    "the change a person must live through",
    "the whole pattern brought into the world"};
static const char *const MARSEILLE_ARC[4] = {
    "The numbered road rises from %s to %s. Each card asks the next practical question of the journey.\n",
    "The numbered road falls from %s to %s. An earlier condition returns, now seen from the experience gained since then.\n",
    "%s in the present is the high point. Past and future show what this central action makes possible.\n",
    "%s in the present is the low point between two stronger pulls. The pause needs a choice or a change of hands.\n",
};
static const char *const MARSEILLE_PLANE[4] = {
    "All three cards belong to %s: %s. Read the details of ordinary life closely; they contain the answer.\n",
    "The reading moves from %s into %s. What begins as %s ends as %s.\n",
    "The reading comes down from %s to %s. An idea is asking for a practical form.\n",
    "Past and future share %s; only the present enters %s. The interruption shows where the work is.\n",
};
static const char *const MARSEILLE_DOMINANT[5] = {
    "Fire is strongest here. Act with courage, but give the action a clear object.\n",
    "Water is strongest here. Attend to feeling, memory and the movement beneath the words.\n",
    "Air is strongest here. Conversation, choice and proportion will change the situation.\n",
    "Earth is strongest here. Look at the body, the money, the room and the work itself.\n",
    "No element leads. The answer is in how the four conditions meet in ordinary life.\n",
};
static const char *const MARSEILLE_TRANSITION[4] = {
    "%s and %s share %s, so the movement between them is direct. Follow the repeated detail.\n",
    "%s (%s) and %s (%s) pull against each other: action meets feeling. Name the choice between them.\n",
    "%s (%s) and %s (%s) pull against each other: thought meets circumstance. Find the action that joins them.\n",
    "%s (%s) feeds %s (%s). This passage has support; use it before the conditions change.\n",
};
const DeckReadingStyle MARSEILLE_READING_STYLE = {
    MARSEILLE_ROW_NAME, MARSEILLE_ROW_GLOSS, MARSEILLE_ARC, MARSEILLE_PLANE,
    MARSEILLE_DOMINANT, MARSEILLE_TRANSITION,
    "The three values total %s. Their reduced card is %s, the quiet condition beneath the spread: %s\n",
    "It is already present in the %s position, so the same lesson is asking to be lived twice.\n",
};
